Repository metatron-app/metatron-discovery, pull requests merged in 2019-02, with the labels that each got.

#1359 #1193 add timezone in pivot
  discovery-frontend/src/app/dashboard/dashboard.module.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/embedded/embedded-view.module.ts
  discovery-frontend/src/app/page/page.module.ts
Labels: @dashboard, testbed2

#1361 #1355 fix config data undefined error
  discovery-frontend/src/app/data-storage/service/granularity.service.ts
Labels: @datasource, testbed1

#1382 #1367 The icon in the results pane disappears when you query the workbench.
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @workbench, testbed2

#1392 #1308 Workspaces are not created under certain conditions in I.E Browser.
  discovery-frontend/src/app/workspace/component/permission/permission-schema.component.html
Labels: @workspace, testbed4

#1411 #1397 remove day timezone
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/data-grid-data-source/data-grid-data-source.component.ts
  discovery-frontend/src/app/data-storage/service/timezone.service.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
  discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/GeoQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeListFilter.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRangeFilter.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilter.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/ContinuousTimeFormat.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormat.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/limits/PivotColumn.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/model/HoltWintersPostProcessor.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
  discovery-server/src/main/resources/scripts/default.sql
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
Labels: @datasource, testbed4

#1366 #1340 'No database selected' error when selecting 'Overwrite only incremental' when creating DB type datasource
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunner.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/JdbcIngestionJob.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunnerIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/fixture/MySqlDatasourceTestFixture.java
  discovery-server/src/test/resources/fixture/mysql/payment.sql
  discovery-server/src/test/resources/sql/test_datasource_list.sql
Labels: @datasource, testbed1

#1402 #1400 Snapshot grid paging processing
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
Labels: @dataprep, testbed5

#1423 fix build error
  discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
  discovery-frontend/src/app/data-storage/service/timezone.service.ts
  discovery-frontend/src/app/page/component/analysis/slider/range-slider.component.ts
Labels: @common, testbed5

#1418 #941 add error message query source create
  discovery-frontend/src/app/common/component/paging-search-select/paging-search-select.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-storage.module.ts
  discovery-frontend/src/app/data-storage/service/data-connection-create.service.ts
  discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
  discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
  discovery-frontend/src/app/workbench/workbench.component.ts
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @datasource, testbed1

#1434 #1376 updated json parsing rules
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Labels: @dataprep, testbed4

#1427 #1406 Fix dataprep main grid css
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
  discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
Labels: @dataprep, testbed4

#1430 #1381 Relplace to html entity(tag symbol,new line)
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
Labels: @dataprep, testbed4

#1410 F#1403 Error showing icons with svg (IE problem)
  discovery-frontend/src/app/common/component/icon/svg-icon.component.html
  discovery-frontend/src/app/common/component/icon/svg-icon.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
  discovery-frontend/src/assets/css/polaris.v2.layout.css
Labels: @dataprep, testbed4

#1424 #667 fix workspace comp in datasource
  discovery-frontend/src/app/data-storage/component/set-workspace-published/set-workspace-published.component.html
  discovery-frontend/src/assets/css/metatron/component/component.table.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @datasource, testbed5

#1426 #1401 Down arrow event in korean input mode.
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.ts
Labels: @dataprep, testbed4

#1432 #1393 Add timestamp format to rename popup data
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-field-combo.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
  discovery-frontend/src/assets/css/polaris.v2.component.css
  discovery-frontend/src/assets/grid/slick.grid.override.css
Labels: @dataprep, testbed5

#1101 #1099 Support Druid SQL
  discovery-frontend/src/app/common/component/abstract.component.ts
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.html
  discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
  discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/jdbc/PrepJdbcService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/DataConnection.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/DruidConnection.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/LiveJdbcEngineRepository.java
Labels: @workbench

#1431 #1275 Memory leaks when maintaining Presentation Mode for long time
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
Labels: @dashboard, testbed2

#1451 F#1350 download file of imported dataset
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
Labels: @dataprep, testbed2

#1465 #1459 Fix histogram click error
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
Labels: @dataprep

#1469 #1464 Add druid icon for workbench is required.
  discovery-frontend/package.json
  discovery-frontend/src/app/common/component/abstract.component.ts
  discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.html
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
  discovery-frontend/src/app/workbench/workbench.component.html
  discovery-frontend/src/app/workbench/workbench.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/images/img_mapchart.png
  discovery-frontend/src/polyfills.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/DataConnectionFilterService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
Labels: @workbench, testbed5

#1429 #1298 Support for regular expressions when entering wildcard filters.
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/domain/workbook/configurations/filter/reg-expr-filter.ts
  discovery-frontend/src/assets/css/metatron/component/component.button.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/RegExprFilter.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
Labels: @dashboard, testbed1

#1467 F#748 make dataset multi sheet excel
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-datatype.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
  discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
  discovery-frontend/src/app/domain/data-preparation/pr-dataset.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @dataprep, testbed2

#1461 #1438 Filters do not apply to line charts.
  discovery-frontend/src/app/common/component/chart/base-chart.ts
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
Labels: @chart, testbed6

#1470 #1238 Remove 'physical' terminology
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema/edit-config-schema.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.html
  discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.html
  discovery-frontend/src/app/page/page-data/page-data-context.component.html
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: testbed5

#1474 #159 Unable to click cancel button and X button when generating metadata
  discovery-frontend/src/app/common/service/abstract.service.ts
  discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.ts
Labels: @metadata, testbed1

#1481 #1464 add druid icon in datasource
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.html
Labels: @datasource, testbed6

#1479 change file create source guide label
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @datasource, bug, testbed3

#1480 #592 Fix error scrolling user list page
  discovery-frontend/src/app/admin/user-management/user-management.component.html
  discovery-frontend/src/app/admin/user-management/user-management.component.ts
Labels: testbed5

#1476 #1464 add double quote to druid table name for workbench data preview
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/DruidConnection.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
Labels: @workbench, testbed2

#1482 #1475 Fix bug from release test
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @dataprep, testbed1

#1290 #944 Improve filter functions for high cardinality columns.
  discovery-frontend/src/app/dashboard/filters/essential-filter/essential-filter.component.ts
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.ts
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.html
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
  discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
  discovery-frontend/src/app/dashboard/update-dashboard.component.html
  discovery-frontend/src/app/dashboard/update-dashboard.component.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/domain/workbook/configurations/filter/inclusion-filter.ts
  discovery-frontend/src/assets/css/metatron/component/component.button.css
  discovery-frontend/src/assets/css/metatron/component/component.checkbox.css
  discovery-frontend/src/assets/css/metatron/component/component.radio.css
  discovery-frontend/src/assets/css/metatron/component/component.search.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/images/icon_checkvalue.png
  discovery-frontend/src/assets/images/icon_info3.png
  discovery-frontend/src/assets/images/icon_radio.png
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/CandidateQueryRequest.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilter.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/Search.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/SearchQuerySpec.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQuery.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/searches/AllSearchQuerySpec.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/searches/FragmentSearchQuerySpec.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/searches/InsensitiveContainsSearchQuerySpec.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/searches/RegexSearchQuerySpec.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilterTest.java
Labels: @dashboard, testbed4

#1498 fix dashboard filter
  discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
Labels: @dashboard, testbed4

#1518 #1477 Fix undefined error in dataset information
  discovery-frontend/src/app/data-preparation/component/dataset-summary.component.ts
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.html
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetDatabaseService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
Labels: @dataprep, testbed3

#1528 transform snapshot uses JSON parser
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
Labels: @dataprep, testbed4

#1530 #1425 If you assign more than 20 users to a user group, only 20 or fewer are exposed
  discovery-frontend/src/app/admin/user-management/component/group/detail-group/detail-user-management-groups.component.ts
  discovery-frontend/src/app/admin/user-management/service/groups.service.ts
Labels: @common, testbed4

#1524 #1447 Filter edit popup error
  discovery-frontend/src/app/dashboard/component/update-dashboard/dashboard.layout.config.component.html
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.html
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
  discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
  discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
  discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
Labels: @dashboard, testbed2

#1533 F#1404 dataprep hive config
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
  discovery-frontend/src/app/data-preparation/data-preparation.module.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-staging-selectdata.component.ts
  discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Labels: @dataprep, testbed2

#1522 #1216 fix script error in workbench chart
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
Labels: @workbench, testbed1

#1543 #1492 bug-fix on BOM of UTF-8
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
Labels: @dataprep, testbed4

#1542 #1375 skip ill-quoted CSV lines
  discovery-distribution/conf/application-config.templete.yaml
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvParseResult.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonParseResult.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSetFormat.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Labels: @dataprep, testbed1

#1544 #1378 fixed a wrong exception handling
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfDelete.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfKeep.java
Labels: @dataprep, testbed2
