Repository metatron-app/metatron-discovery, pull requests merged in 2019-01, with the labels that each got.

#1174 #1168 remove value validation in dataconnection custom prop.
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.ts
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.html
  discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.ts
Labels: @datasource, testbed3

#1200 #1141 added_preparation_custom_patch_controller
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetJdbcService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
Labels: @dataprep, testbed5

#1196 #1173 Add rule list in dataset detail - wrangled
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @dataprep, testbed6

#1195 #725 fix partition keys in source detail
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
Labels: @datasource

#1194 #740 remove url link in connection list
  discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-dataconnection-info/detail-workbench-dataconnection-info.html
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.html
Labels: @datasource, testbed4

#1111 #973 Sorting function of data table does not work properly.
  discovery-frontend/src/app/page/page.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/fixture/SalesGeoDataSourceTestFixture.java
  discovery-server/src/test/resources/ingestion/sales_geo.csv
Labels: @chart, testbed1

#1211 #803 need to go to the detail page right after creating the workbench
  discovery-frontend/src/app/notebook/component/create-notebook/create-notebook-name/create-notebook-name.component.ts
  discovery-frontend/src/app/notebook/component/create-notebook/create-notebook.component.ts
  discovery-frontend/src/app/workbench/component/create-workbench/create-workbench-complete/create-workbench-complete.component.ts
  discovery-frontend/src/app/workspace/component/etc/set-notebook-server.component.html
  discovery-frontend/src/app/workspace/workspace.component.html
  discovery-frontend/src/app/workspace/workspace.component.ts
Labels: @workspace, testbed2

#1206 #1205 Modify the link to the Github issue in the README file
  README.md
Labels: @common

#1218 F#1186 edit snapshot name
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/service/data-snapshot.service.ts
  discovery-frontend/src/app/domain/data-preparation/pr-snapshot.ts
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @dataprep, testbed1

#1219 #640 Fix phrase in job log detail
  discovery-frontend/src/app/monitoring/audit/job-log/component/job-detail/job-detail.component.html
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @datamonitoring, testbed1

#1225 #743 add sql beautifier and save
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @workbench, testbed4

#1236 #160 Error display for counted row on text table(grid)
  discovery-frontend/src/app/common/component/chart/type/grid-chart/grid-chart.component.ts
  discovery-frontend/src/app/page/chart-style/calrow-option.component.html
  discovery-frontend/src/app/page/chart-style/calrow-option.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
Labels: @chart, testbed5

#1177 Apply static resource caching
  discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
  discovery-server/src/main/resources/application.yaml
Labels: @common, testbed3

#1232 #1159 Support for querying data in a table with a very large number of columns
  discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorResult.java
Labels: @workbench

#1153 #972 If the data table dimension is 3, and the measure value is 2, the browser does not work
  discovery-frontend/src/app/common/component/chart/base-chart.ts
Labels: @chart, testbed2

#1244 F#1233 improve scrolling in metadata
  discovery-frontend/src/app/meta-data-management/code-table/create-code-table/create-code-table.component.html
  discovery-frontend/src/app/meta-data-management/column-dictionary/create-column-dictionary/create-column-dictionary.component.html
  discovery-frontend/src/app/meta-data-management/meta-data-management.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/complete-create-metadata.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/ds-select-datasource.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/ds-select-datasource.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-set-connection.component.html
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.html
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @metadata, testbed2

#1239 F#1220 polling error in snapshot list
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.ts
Labels: @dataprep, testbed6

#1240 #1059 add type constraint in schema component
  discovery-frontend/src/app/common/util/string.util.ts
  discovery-frontend/src/app/data-storage/component/schema-change-action/schema-change-action.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-action-bar.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-action-bar.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
  discovery-frontend/src/app/data-storage/component/schema-detail/schema-detail.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-ingestion-permission/db-ingestion-permission.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-ingestion/file-ingestion.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-ingestion/staging-db-ingestion.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-select-data/staging-db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-storage.module.ts
  discovery-frontend/src/app/domain/datasource/datasource.ts
  discovery-frontend/src/app/workbench/workbench.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.checkbox.css
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.05Management_Create.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/images/icon_info.png
Labels: @datasource, testbed4

#1241 F#1121 wrong dataset summary
  discovery-frontend/src/app/common/component/select/select.component.html
  discovery-frontend/src/app/common/component/select/select.component.ts
  discovery-frontend/src/app/data-preparation/component/dataset-summary.component.html
  discovery-frontend/src/app/data-preparation/component/dataset-summary.component.ts
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.ts
  discovery-frontend/src/app/data-preparation/data-preparation.module.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/add-dataset.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/add-dataset.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/add-dataset-modal/add-dataset-modal.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/add-dataset-modal/add-dataset-modal.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
Labels: @dataprep, testbed2

#1204 Add weblink for user guidance into LNB
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @common, testbed2

#1201 F#1184 show aggregation warning
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.html
  discovery-frontend/src/assets/css/metatron/component/component.search.css
  discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/images/icon_error.png
Labels: @dataprep, testbed6

#1249 F#795 horizontal scroll in histogram area
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
  discovery-frontend/src/assets/css/polaris.v2.component.css
Labels: @dataprep, testbed6

#1261 #1260 histogram never fails no matter how wide the timestamp range is
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java
Labels: @dataprep, testbed6

#1250 #968 The records in the data table do not match the actual data.
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/assets/css/metatron/page/metatron.page.02Workbook_Chart.css
Labels: @chart, testbed1

#1254 #1215 roll up false for chart preview
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @datasource, @workbench, testbed2

#1252 Fix job property guide into StagingDB ingestion option.
  discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.html
  discovery-frontend/src/assets/css/metatron/component/component.tooltip.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @datasource, testbed3

#1265 #1064 Support for adding basemap in mapview via configuration
  discovery-frontend/src/app/common/component/chart/option/util/option-generator.ts
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
  discovery-frontend/src/app/common/constant/common.constant.ts
  discovery-frontend/src/app/dashboard/service/widget.service.ts
  discovery-frontend/src/app/page/chart-style/map/map-common-option.component.ts
  discovery-frontend/src/app/workbook/workbook.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetProperties.java
  discovery-server/src/main/resources/application.yaml
  discovery-server/src/test/java/app/metatron/discovery/domain/workbook/widget/WidgetRestIntegrationTest.java
Labels: @chart, testbed6

#1262 F#1077 add icons regarding snapshot
  discovery-frontend/src/app/common/common.module.ts
  discovery-frontend/src/app/common/component/icon/svg-icon.component.html
  discovery-frontend/src/app/common/component/icon/svg-icon.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
  discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
  discovery-frontend/src/assets/css/metatron/component/component.icon.css
  discovery-frontend/src/assets/css/metatron/component/component.icons.css
  discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/images/icon_flow.png
  discovery-frontend/src/assets/images/icon_snapshot_status.png
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshot.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshotProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/resources/application.yaml
Labels: @dataprep, testbed5

#1271 F#1171 dataprep shows user full name
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.html
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
  discovery-frontend/src/app/data-preparation/dataset/dataset.component.html
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDataflowProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDatasetProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshotProjections.java
Labels: testbed3

#1272 F#0 fix metadata error
  discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.html
  discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/ds-select-datasource.component.html
  discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.ts
Labels: testbed3

#1273 #1064 fix error when creating map chart
  discovery-frontend/src/app/common/component/chart/base-chart.ts
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
  discovery-frontend/src/app/page/chart-style/map/map-common-option.component.ts
  discovery-frontend/src/assets/i18n/ko.json
Labels: @chart, testbed2

#1269 Fix date range format (Add T for time)
  discovery-frontend/src/app/common/common.module.ts
  discovery-frontend/src/app/common/component/chart/base-chart.ts
  discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
  discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
  discovery-frontend/src/app/common/component/chart/option/ui-option/ui-label-chart.ts
  discovery-frontend/src/app/common/component/chart/type/gauge-chart/gauge-chart.component.ts
  discovery-frontend/src/app/common/component/chart/type/grid-chart/grid-chart.component.ts
  discovery-frontend/src/app/common/component/chart/type/label-chart/label-chart.component.ts
  discovery-frontend/src/app/common/component/chart/type/pie-chart/pie-chart.component.ts
  discovery-frontend/src/app/common/component/chart/type/wordcloud-chart/wordcloud-chart.component.ts
  discovery-frontend/src/app/common/component/icon/svg-icon.component.html
  discovery-frontend/src/app/common/component/icon/svg-icon.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
  discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
  discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.html
  discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
  discovery-frontend/src/app/data-storage/service/granularity.service.ts
  discovery-frontend/src/app/page/chart-style/color-option.component.html
  discovery-frontend/src/app/page/chart-style/color-option.component.ts
  discovery-frontend/src/app/page/chart-style/common-option.component.html
  discovery-frontend/src/app/page/chart-style/common-option.component.ts
  discovery-frontend/src/app/page/chart-style/secondary-indicator.component.ts
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.html
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.icon.css
  discovery-frontend/src/assets/css/metatron/component/component.icons.css
  discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/images/icon_flow.png
  discovery-frontend/src/assets/images/icon_snapshot_status.png
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshot.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshotProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/resources/application.yaml
Labels: testbed1

#1286 F#1284 initialize time after retry
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @workbench, bug, testbed2

#1285 #1092 if string unix type, convert to number type
  discovery-frontend/src/app/data-storage/service/granularity.service.ts
  discovery-frontend/src/assets/css/metatron/component/component.form.css
Labels: @datasource, bug, testbed1

#1294 #463 bar chart change the dimension value when row, aggregation
  discovery-frontend/src/app/page/page.component.ts
Labels: @chart, testbed2

#1312 f#1311 Fix Metadata list when popularity is null
  discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataPopularityService.java
  discovery-server/src/test/java/app/metatron/discovery/domain/mdm/MetadataRestIntegrationTest.java
  discovery-server/src/test/resources/sql/test_mdm_popularity.sql
Labels: @metadata, testbed4

#1313 Support Chinese currency on the chart.
  discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
  discovery-frontend/src/app/common/component/chart/option/define/common.ts
  discovery-frontend/src/app/page/chart-style/format/format-item.component.ts
Labels: @chart, enhancement, testbed1

#1297 #1276 Remove unusing fields into SelectMeta Query.
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectMetaQueryBuilder.java
Labels: @common, @datasource, testbed3

#1164 #1129 The data represented in the chart does not match the download data
  discovery-frontend/src/app/common/component/data-download/data.download.component.ts
  discovery-frontend/src/app/dashboard/service/widget.service.ts
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
  discovery-frontend/src/app/domain/datasource/data/search-query-request.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/BoardConfiguration.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java
Labels: @dashboard, testbed5

#1314 #1300 Fix tooltip z-index
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.html
Labels: @dataprep, testbed6

#1323 F#1296 Fix information in snapshot detail
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset.component.html
  discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
  discovery-frontend/src/app/domain/data-preparation/pr-snapshot.ts
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @dataprep, testbed1

#1330 F#1221 dataprep test case refactoring
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetJdbcService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvInputTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/rest/PrDataflowRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/rest/PrDatasetRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/rest/PrSnapshotRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/rest/PrepTransformRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/OrcTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/SetTypeTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/TeddyTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/UnstructuredTest.java
  discovery-server/src/test/resources/csv/multi_line_with_bs_escape.csv
Labels: @dataprep, testbed5

#1333 F#1246 dataprep contoller code cleaning
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetDatabaseService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileUploadAsyncConfig.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileUploadService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepException.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowEventHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetEventHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
Labels: @dataprep, testbed5

#1336 F#1289 new suggestion window aggregate pivot
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule/suggest/rule.suggest.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfAggregate.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfPivot.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/AggregateTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/OrcTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/PivotTest.java
Labels: @dataprep, testbed5

#1328 #1057 enhance ingest validation
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
  discovery-frontend/src/app/data-storage/data-storage.module.ts
  discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
  discovery-frontend/src/app/domain/datasource/datasource.ts
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.05Management_Create.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/FileValidationResponse.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/IngestionDataResultResponse.java
  discovery-server/src/main/java/app/metatron/discovery/util/CsvProcessor.java
  discovery-server/src/main/java/app/metatron/discovery/util/ExcelProcessor.java
Labels: @datasource, testbed3

#1332 #1274 Checkbox global filter widget does not work properly
  discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.html
  discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.ts
  discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
  discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
Labels: @dashboard, testbed4

#1334 F#1319 fix rename popup
  discovery-frontend/src/app/data-preparation/data-preparation.module.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/images/icon_dataview.png
Labels: @dataprep, testbed2

#1343 F#1306 using uri to create a file type snapshot
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotRequestPost.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshot.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/rest/PrSnapshotRestIntegrationTest.java
Labels: @dataprep, testbed2

#1346 #1345 use the delimiter for snapshots
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
Labels: @dataprep, testbed2

#1348 #1296 Show tooltip when snapshot file uri is shortened
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html
Labels: @dataprep, testbed5

#1342 Change row parser to string on hadoop ingestion
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
Labels: @datasource

#1353 #199 fix error input component
  discovery-frontend/src/app/common/component/input/input.component.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-complete.component.html
  discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
  discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.html
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
  discovery-frontend/src/app/meta-data-management/catalog/catalog.component.html
  discovery-frontend/src/app/meta-data-management/code-table/code-table.component.html
  discovery-frontend/src/app/meta-data-management/column-dictionary/column-dictionary.component.html
  discovery-frontend/src/app/meta-data-management/metadata/metadata.component.html
Labels: @dashboard, testbed2

#1351 f#0-fix_range_slider fixed range slider
  discovery-frontend/src/app/page/component/analysis/slider/range-slider.component.ts
Labels: @chart, bug, testbed5
