Repository metatron-app/metatron-discovery, pull requests merged in 2019-05, with the labels that each got.

#1934 Internationalize mailing template
  discovery-server/src/main/java/app/metatron/discovery/common/Mailer.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
  discovery-server/src/main/java/app/metatron/discovery/util/PolarisUtils.java
  discovery-server/src/main/resources/messages/messages.properties
  discovery-server/src/main/resources/messages/messages_en.properties
  discovery-server/src/main/resources/messages/messages_ko.properties
  discovery-server/src/main/resources/templates/api/email/user_reset_password.html
  discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
  discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
  discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
  discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
  discovery-server/src/main/resources/templates/api/email/user_signup_request.html
Labels: testbed2

#1935 #1882 About Liner Predictive
  discovery-frontend/src/app/common/component/input/input.component.ts
  discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.html
  discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
  discovery-frontend/src/app/page/page.component.ts
Labels: @chart, testbed3

#1961 #1901 filter; if two table has same column names, it cannot apply to both table
  discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
  discovery-frontend/src/app/dashboard/update-dashboard.component.ts
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
Labels: @dashboard, testbed5

#1981 #1954 Unnecessary pop-ups when creating datasource via workbench
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/create-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
  discovery-frontend/src/app/workbench/workbench.component.html
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @datasource, @workbench, testbed2

#1983 Fn fix extension dbtype workbench
  discovery-frontend/src/app/workbench/component/create-workbench/create-workbench-select/create-workbench-select.component.html
  discovery-frontend/src/app/workbench/component/create-workbench/create-workbench-select/create-workbench-select.component.ts
Labels: @workbench, testbed6

#1982 fn fix checkbox in notebook list
  discovery-frontend/src/app/model-management/notebook-server/notebook-server.component.html
  discovery-frontend/src/app/model-management/notebook-server/notebook-server.component.ts
Labels: @notebook, testbed3

#1967 #1517 fix an error in retrieving the list of movable workspaces
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceRepositoryImpl.java
  discovery-server/src/test/java/app/metatron/discovery/domain/workspace/WorkspaceRestIntegrationTest.java
  discovery-server/src/test/resources/sql/test_import_workspace_list.sql
Labels: @workspace, testbed4

#1986 fn ie issue when table select in workbench
  discovery-frontend/src/app/workbench/workbench.component.html
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @workbench, testbed5

#1987 Save button activation error when editing profile image
  discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
  discovery-frontend/src/app/user/profile/profile.component.html
  discovery-frontend/src/app/user/profile/profile.component.ts
Labels: @common, testbed6

#1980 #1948 date function for incremental ingestion
  discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/dialect/JdbcDialect.java
  discovery-extensions/mssql-connection/src/main/java/app/metatron/discovery/MssqlConnectionExtension.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/DruidDialect.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/HiveDialect.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/MySQLDialect.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PrestoDialect.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceErrorCodes.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceEventHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SelectQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunner.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/JdbcIngestionJob.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SelectQueryBuilderTest.java
Labels: @datasource, testbed1

#1985 Fix broken css in ie (2)
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/select-type/select-type.component.html
  discovery-frontend/src/app/domain/datasource/datasource.ts
  discovery-frontend/src/app/monitoring/audit/log-statistics/log-statistics.detail.component.html
  discovery-frontend/src/app/monitoring/audit/log-statistics/log-statistics.detail.component.ts
  discovery-frontend/src/app/page/page.component.html
  discovery-frontend/src/assets/css/metatron/component/component.tooltip.css
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/images/icon_lnb.png
Labels: @common, testbed2

#1988 #1940 Improved UI performance when column content size is long on ingestion stage
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-data-preview.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-data-preview.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/druid-create-component/druid-select/druid-select.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-select-data/staging-db-select-data.component.ts
  discovery-frontend/src/app/domain/datasource/datasource.ts
Labels: @datasource

#1992 Remove useless terms on bottoms of accounts mail
  discovery-server/src/main/resources/templates/api/email/user_reset_password.html
  discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
  discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
  discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
  discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
  discovery-server/src/main/resources/templates/api/email/user_signup_request.html
Labels: testbed2

#1993 Allow special characters on the User APIs
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
  discovery-server/src/test/java/app/metatron/discovery/domain/user/UserRestIntegrationTest.java
  discovery-server/src/test/resources/sql/test_user_delete.sql
Labels: testbed6

#1997 Fixed a UI error
  discovery-frontend/package.json
  discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/linked-resources/detail-workspace-linked-resources.component.html
  discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/viewer/resources-view.component.html
  discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.html
  discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-sort.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-frontend/src/app/workbook/workbook.component.html
  discovery-frontend/src/app/workbook/workbook.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.table.css
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: testbed1

#2002 #1969 Custom color settings in map charts are initialized when changing other filter conditions
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
Labels: testbed2

#1995 Support various type of delimiter on hive ingestion
  discovery-server/src/main/java/app/metatron/discovery/KeepAsUnescapeSerializer.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/file/CsvFileFormat.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/CsvParseSpec.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/TsvParseSpec.java
  discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/parser/ParseSpecTest.java
Labels: testbed3

#2000 Fixed errors on charts and datasources.
  discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
  discovery-frontend/src/app/common/component/chart/type/line-chart/line-chart.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
  discovery-frontend/src/app/domain/meta-data-management/metadata-column.ts
  discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.html
  discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
  discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
Labels: @chart, @datasource, testbed1

#2018 Remove 'typeString' property in ingestion spec.
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
  discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
Labels: @datasource

#2017 #2012 Can not access workbook in a workspace which is allowed anyone to access
  discovery-frontend/src/app/domain/workspace/workspace.ts
Labels: @workspace, testbed5

#2004 #1966 Fixed number sorting.
  discovery-frontend/src/app/common/component/grid/grid.component.ts
Labels: @datasource, testbed1

#2011 #1816 Disable file upload in file uploading status
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.ts
Labels: @datasource, testbed2

#2020 #2009 dataflow icon error in ie
  discovery-frontend/src/app/common/component/icon/svg-icon.component.html
  discovery-frontend/src/app/common/component/icon/svg-icon.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail2.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/images/datapreparation/png/icon_AmazonRedshift.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_AmazonRedshift_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_add.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_custom.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_custom_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_dataset_wrangled_.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_dataset_wrangled_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_hive.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_hive_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_mysql.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_mysql_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_oracle.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_oracle_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_phoenix.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_phoenix_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_post.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_post_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_presto.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_presto_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_tibero.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_db_tibero_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_druid.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_druid_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_csv.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_csv_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_json.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_json_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_txt.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_txt_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_xls.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_xls_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_xlsx.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_file_xlsx_focus.png
  discovery-frontend/src/assets/images/datapreparation/png/icon_flow_delete.png
  discovery-frontend/src/assets/images/datapreparation/png/img_xlsx.png
Labels: @dataprep, testbed1

#2021 #1850 The user must not move the workbook to a workspace with watcher privileges
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceRepositoryImpl.java
Labels: @common, testbed2

#2028 #1996 Some unnatural translations
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @common, testbed1

#2019 #1889 Script error when moving to previous page of workbench
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @workbench, testbed5

#2013 #1925 Fix combobox in create datasource schema step
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-action-bar.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/component/add-column.component.html
  discovery-frontend/src/app/data-storage/data-source-list/component/add-column.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/component/storage-filter-select-box.component.html
  discovery-frontend/src/app/data-storage/data-source-list/component/storage-filter-select-box.component.ts
Labels: @datasource, testbed3

#2032 #1990 Improve phrase connection info
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.ts
  discovery-frontend/src/app/data-storage/component/connection/connection.component.html
  discovery-frontend/src/app/data-storage/component/connection/connection.component.ts
  discovery-frontend/src/app/data-storage/data-connection/create-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/create-connection.component.ts
  discovery-frontend/src/app/data-storage/data-connection/update-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/update-connection.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @datasource, testbed1

#2052 #1989 hide geo type column from the filtering list
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.html
Labels: @datasource, testbed3

#2042 #1231 Show appropriate error message in join popup
  discovery-frontend/src/app/common/component/abstract.component.ts
  discovery-frontend/src/app/common/util/alert.util.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.html
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.ts
  discovery-frontend/src/app/layout/layout/layout/layout.component.ts
  discovery-frontend/src/assets/css/metatron/polaris.metatron.page.css
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.02Workbook_Dashboard_join.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @dashboard, testbed5

#2056 #1890 enhance presto connection valid check if it is an invalid catalog
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/PrestoDataAccessor.java
Labels: @datasource, testbed3

#2055 #1309 fix displaying array type of column on presto connection
  discovery-server/pom.xml
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriterTest.java
Labels: @datasource, @workbench, testbed1

#2022 #1904 long txt error in chart shelf
  discovery-frontend/src/app/common/component/select/select.component.html
  discovery-frontend/src/app/common/component/select/select.component.ts
  discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.html
  discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.html
  discovery-frontend/src/app/page/chart-style/color-option.component.html
  discovery-frontend/src/app/page/page-data/page-data-context.component.html
  discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.html
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.html
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
  discovery-frontend/src/app/page/page.component.html
  discovery-frontend/src/assets/css/metatron/component/component.button.css
  discovery-frontend/src/assets/css/metatron/component/component.checkbox.css
  discovery-frontend/src/assets/css/metatron/component/component.radio.css
  discovery-frontend/src/assets/css/metatron/component/component.selectbox.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @chart, testbed4

#2054 #2023 change the partition validation feature visibility
  discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/storage/MetaStoreProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
  discovery-server/src/main/resources/application.yaml
Labels: @datasource, testbed5

#2014 #1921 The number of data sources in the workspace UIs are different
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-ds-select.component.html
  discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.html
  discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
  discovery-frontend/src/app/layout/layout/layout/layout.component.ts
  discovery-frontend/src/app/workspace/component/etc/data-source.component.html
  discovery-frontend/src/app/workspace/component/etc/data-source.component.ts
  discovery-frontend/src/app/workspace/component/permission/shared-member.component.html
  discovery-frontend/src/app/workspace/component/permission/shared-member.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.table.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-frontend/src/assets/images/icon_disabled.png
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourcePredicate.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
  discovery-server/src/test/java/app/metatron/discovery/domain/workspace/WorkspaceRestIntegrationTest.java
  discovery-server/src/test/resources/sql/test_datasource_in_workspace.sql
Labels: @workspace, testbed3

#2058 #2036 Need a submit button to time filter in dashboard
  discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
  discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @dashboard, testbed1

#2038 F#1965 not working multi line string geometry
  discovery-frontend/src/app/common/component/chart/option/define/map/map-common.ts
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-server/src/main/java/app/metatron/discovery/common/geospatial/geojson/GeoJsonGeometry.java
  discovery-server/src/main/java/app/metatron/discovery/common/geospatial/geojson/GeoJsonWriter.java
  discovery-server/src/main/java/app/metatron/discovery/common/geospatial/geojson/LineStringGeometry.java
  discovery-server/src/main/java/app/metatron/discovery/common/geospatial/geojson/MultiLineStringGeometry.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
Labels: @chart, testbed2

#2096 maintain filters in list after deleting
  discovery-frontend/src/app/meta-data-management/code-table/detail-code-table/detail-code-table.component.ts
  discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.ts
Labels: testbed2

#2097 Remove stage connection from filter criteria in data-connection list
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java
Labels: @datasource, testbed3

#2099 Fixed an error in creating a user field of a name
  discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-ds-select.component.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
  discovery-frontend/src/app/workbook/workbook.component.html
  discovery-frontend/src/app/workbook/workbook.component.ts
  discovery-frontend/src/app/workspace/component/management/workspace-list.component.html
  discovery-frontend/src/app/workspace/component/management/workspace-list.component.ts
Labels: @dashboard, @workspace, testbed2

#2098 Fixed missing unionAll query spec
  discovery-server/src/main/java/app/metatron/discovery/query/druid/datasource/UnionDataSource.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
Labels: testbed4

#2095 Fix alert error in data preview
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
Labels: @datasource, bug, testbed1

#2102 Fixed an error when creating a chart for the first time
  discovery-frontend/src/app/datasource/service/datasource.service.ts
Labels: testbed1

#2106 Error when deleting last item in the list
  discovery-frontend/src/app/admin/user-management/component/group/detail-group/detail-user-management-groups.component.ts
  discovery-frontend/src/app/admin/user-management/component/group/update-group/update-user-management-groups.component.html
  discovery-frontend/src/app/admin/user-management/component/group/user-management-groups.component.ts
  discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.ts
  discovery-frontend/src/app/admin/user-management/component/members/user-management-members.component.ts
  discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/permission-schemas.component.ts
  discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
  discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
  discovery-frontend/src/app/data-storage/data-connection/data-connection.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.ts
  discovery-frontend/src/app/meta-data-management/code-table/code-table.component.ts
  discovery-frontend/src/app/meta-data-management/column-dictionary/column-dictionary.component.ts
Labels: testbed3

#2108 Add api documentation as draft version
  discovery-server/pom.xml
  discovery-server/src/main/asciidoc/api-datasource-guide.adoc
  discovery-server/src/main/asciidoc/api-datasource-query-guide.adoc
  discovery-server/src/main/asciidoc/api-guide.adoc
  discovery-server/src/main/asciidoc/api-workbook-guide.adoc
  discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
Labels: @common, testbed1

#2109 Css issues in workbench and workbook
  discovery-frontend/src/app/page/page-data/page-data-context.component.html
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-navigation/detail-workbench-navigation.html
  discovery-frontend/src/assets/css/metatron/component/component.button.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: testbed3

#2110 Hide folders when filter is applied
  discovery-frontend/src/app/workspace/workspace.component.html
Labels: testbed1

#2112 Disable next and previous button in paging component
  discovery-frontend/src/app/common/component/pagination/pagination.component.html
  discovery-frontend/src/app/common/component/pagination/pagination.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.page.css
Labels: testbed4

#2107 fix list workspace for publish at data storage
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspacePredicate.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
Labels: @workspace, testbed2

#2113 Change manual link in the LNB
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
Labels: testbed3

#2114 Adding Constraints to Join Fields & Modify the Save Workbench Results feature
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.html
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.ts
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
  discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.html
  discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: testbed1

#2118 Fix format error in metadata schema
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
  discovery-frontend/src/app/shared/datasource-metadata/component/datetime-valid-popup.component.html
  discovery-frontend/src/app/shared/datasource-metadata/component/datetime-valid-popup.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.selectbox.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataColumnProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataEventHandler.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/mdm/MetadataRestIntegrationTest.java
  discovery-server/src/test/resources/sql/test_mdm.sql
Labels: @metadata, bug, testbed3

#2129 Fix prediction line errors
  discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
Labels: @chart, testbed1

#2145 #2144 Explicit GC in snapshot when polaris.dataprep.etl.explicitGC=true
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
Labels: @dataprep
