Repository metatron-app/metatron-discovery, pull requests merged in 2019-03, with the labels that each got.

#1525 #1472 remove adding unnecessary advanced filter specification even if doing nothing
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
  discovery-frontend/src/app/dashboard/update-dashboard.component.ts
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/page/page.component.ts
Labels: @chart, testbed3

#1563 #1562 added limitation on DOP when calculating the histograms
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Labels: @dataprep, testbed4

#1546 F#1468 snapshot compression error
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
  discovery-frontend/src/app/data-preparation/data-preparation.module.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/service/data-snapshot.service.ts
  discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.service.ts
  discovery-frontend/src/app/domain/data-preparation/pr-snapshot.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @dataprep, testbed2

#1567 F#1532 fix dataprep name input
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @dataprep, testbed2

#1565 #1380 changed new column order of window rules
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
Labels: @dataprep, testbed4

#1569 #1568 bug-fix on header processing of CSV files
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
Labels: @dataprep, testbed6

#1561 #1444 Multiple filter selection error
  discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.ts
Labels: @dashboard, testbed2

#1560 F#1489 A sort error occurs if the data grid contains blanks
  discovery-frontend/src/app/common/component/grid/grid.component.ts
  discovery-frontend/src/assets/grid/slick.grid.override.css
Labels: @workbench, testbed3

#1585 F#1579 add snapshot table name validation
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.form.css
  discovery-frontend/src/assets/css/polaris.v2.component.css
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-frontend/src/assets/images/icon_info3.png
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Labels: @dataprep, testbed6

#1566 #1494 convert TIMESTAMP field's datatype to STRING
  discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
Labels: @workbench, testbed5

#1574 #1446 Date/Time filter granularity change error
  discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
  discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
Labels: @dashboard, testbed2

#1572 #1496 check segment's status for temporary datasource
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
Labels: @datasource, @workbench, testbed4

#1571 #1570 JupyterBuilder.java Invalid SPARK_HOME setting
  discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/JupyterBuilder.java
Labels: @workspace

#1584 #1564 It is not possible to create a new workbench by returning too many connection lists.
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
Labels: @workbench, testbed2

#1595 Fn dataprep release fix
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
Labels: @dataprep, testbed4

#1589 #1515 Multi file import function and large file upload function in prep
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset.component.ts
  discovery-frontend/src/app/domain/data-preparation/pr-dataset.ts
  discovery-frontend/src/assets/css/metatron/component/component.loading.css
  discovery-frontend/src/assets/css/metatron/polaris.metatron.page.css
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.05Management_Create.css
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-frontend/src/assets/images/icon_flow.png
Labels: @dataprep, testbed2

#1597 F#0 Modifying the font color when the metadata has no explanation
  discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-information.component.html
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @metadata, testbed6

#1602 Fix datasource, group release error
  discovery-frontend/src/app/admin/user-management/component/group/create-group/create-user-management-groups.component.html
  discovery-frontend/src/app/admin/user-management/component/group/create-group/create-user-management-groups.component.ts
  discovery-frontend/src/app/common/util/string.util.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
  discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.html
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @datasource, testbed5

#1600 F#1209 Show the workbench connection information from the contents list in the workspace
  discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
  discovery-frontend/src/app/domain/workspace/book.ts
  discovery-frontend/src/app/workspace/workspace.component.html
  discovery-frontend/src/app/workspace/workspace.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-server/src/main/java/app/metatron/discovery/domain/workbench/Workbench.java
  discovery-server/src/test/resources/sql/test_workbook.sql
Labels: @workspace, testbed4

#1593 #1489 add prefix 'anonymous' if column label is empty.
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
Labels: @workbench, testbed3

#1606 F#0 Add guideline if metadata value does not exist
  discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.html
  discovery-frontend/src/assets/css/metatron/component/component.search.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
Labels: @metadata, testbed2

#1607 #0 fix error that dashboard
  discovery-frontend/src/app/common/component/chart/type/waterfall-chart/waterfall-chart.component.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.html
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
  discovery-frontend/src/app/dashboard/component/update-dashboard/text-widget-panel.component.html
  discovery-frontend/src/app/dashboard/update-dashboard.component.html
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @dashboard, testbed5

#1619 f#0-fn-dataprep-create-dataset-fix fix create dataset with multi files
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
Labels: @dataprep, testbed4

#1617 #fn use ordered map for JSON snapshot. bug-fix on CSV snapshot.
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
Labels: @dataprep, testbed2

#1620 adjust margin button and panel / fix error when remove result tab in workbench
  discovery-frontend/src/app/dashboard/component/update-dashboard/dashboard.layout.config.component.html
  discovery-frontend/src/app/workbench/workbench.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: testbed4

#1622 #fn add spec backward for geoshelf and fix duplicated query id
  discovery-server/src/main/java/app/metatron/discovery/common/CommonLocalVariable.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/widget/shelf/GeoShelf.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GeoBoundaryFilterQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
  discovery-server/src/test/resources/sql/test_gis_datasource.sql
Labels: @chart, testbed2

#1621 #0 Change when to invoke the Stage DB Activation Check API
  discovery-frontend/src/app/common/gaurd/stagedb-enabled.guard.ts
  discovery-frontend/src/app/data-storage/service/storage.service.ts
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
  discovery-frontend/src/app/layout/layout/layout.module.ts
Labels: @dataprep, @datasource, @metadata, testbed5

#1615 Fix row number error in file datasource create
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
Labels: @datasource, testbed3

#1614 F#1613 attribute typo in csv file format delimiter
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/HiveTableInformation.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/file/CsvFileFormat.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
Labels: @datasource, testbed1

#1624 Support array column type by api
  discovery-server/src/main/antlr4/app/metatron/discovery/query/polaris/Expr.g4
  discovery-server/src/main/java/app/metatron/discovery/common/datasource/LogicalType.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/DimensionSchema.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/DimensionsSpec.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
  discovery-server/src/test/resources/ingestion/sample_ingestion_array.json
  discovery-server/src/test/resources/sql/test_datasource_array.sql
Labels: testbed1

#1637 F#1599 wrong stage idx after redo
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfMerge.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Revision.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Labels: @dataprep, bug, testbed2

#1633 F#1632 fix conf template
  discovery-server/src/main/resources/application.yaml
Labels: @dataprep

#1646 #1490 Add Double quote when you click on table name of LNB of Druid workbench
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts
  discovery-frontend/src/app/workbench/workbench.component.html
Labels: @workbench, testbed1

#1652 #1651 upload files to finaldestination
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrUploadFile.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/repository/PrUploadFileRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
Labels: @dataprep, testbed2

#1658 #1541 In Hive snapshots, dataprep array type is store as Hive arrays
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/ColumnDescription.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyOrcWriter.java
Labels: @dataprep, testbed4

#1661 error display time due to processing time zone (backward compatibility for changing time format)
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/ContinuousTimeFormat.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormat.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
Labels: testbed2

#1666 F#1594 set max chars per column for csv parse
  discovery-server/src/main/java/app/metatron/discovery/common/MetatronProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbench/hive/WorkbenchHiveService.java
  discovery-server/src/main/java/app/metatron/discovery/util/CsvProcessor.java
  discovery-server/src/main/java/app/metatron/discovery/util/csv/CsvTemplate.java
Labels: @datasource, testbed2

#1669 Fix setting parameter name (timezone -> timeZone)
  discovery-frontend/src/app/common/component/chart/type/label-chart/label-chart.component.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
  discovery-frontend/src/app/domain/datasource/data/time-compare-request.ts
  discovery-frontend/src/app/domain/workbook/configurations/filter/time-relative-filter.ts
Labels: @dashboard, testbed2

#1662 #1638 save scroll position in rename
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
Labels: @dataprep, testbed4

#1663 #1647 fix dataset name max length
  discovery-frontend/src/app/common/component/icon/svg-icon.component.html
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset.component.html
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @dataprep, testbed3

#1677 #1379 fix suggestion layer direction
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-set.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.model.service.ts
  discovery-frontend/src/app/data-preparation/util/prep-select-box-custom.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.selectbox.css
  discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @dataprep, testbed3

#1674 #1665 Remove alert when fetching staging db returns error
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
Labels: @dataprep, testbed4

#1673 #1667 bug-fix in histogram when long label values overflow
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepHistogramService.java
Labels: @dataprep, testbed2

#1657 #1495 An error occurs when using reserved words for field names.
  discovery-frontend/src/app/workbench/workbench.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
Labels: @datasource, @workbench, testbed1

#1668 #1631 Some UX improvements when creating datasets with multiple file uploads.
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/app/domain/data-preparation/pr-dataset.ts
  discovery-frontend/src/assets/css/metatron/component/component.icons.css
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-frontend/src/assets/images/icon_reset.png
Labels: @dataprep, testbed5

#1689 #1588 Fix parameter when database is presto and postgre
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
Labels: @dataprep, testbed3

#1697 #1516 make dataflow short cut
  discovery-frontend/src/app/data-preparation/component/checkbox-select-dataset.component.html
  discovery-frontend/src/app/data-preparation/component/checkbox-select-dataset.component.ts
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.html
  discovery-frontend/src/app/data-preparation/data-preparation.module.ts
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.model.service.ts
  discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-datatype.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-staging-selectdata.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-frontend/src/app/domain/data-preparation/pr-dataset.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @dataprep, testbed3

#1698 #1664 Data preview fails when creating data source
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
Labels: @datasource, testbed4

#1691 #1690 hive table description bug fix (start row 2 => 0)
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
Labels: @datasource, testbed2

#1707 #796 allow cell copy
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.ts
Labels: @dataprep, testbed3

#1700 #1331 column rename for hive snapshot
  discovery-frontend/package.json
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
  discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.html
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail2.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
Labels: @dataprep, testbed5

#1710 #1693 Show file upload location when creating dataset with file
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
Labels: @dataprep, testbed4

#1712 #1681 name after W.DS not I.DS
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Labels: @dataprep, testbed5

#1709 F#1374 determining column count on file datasets
  discovery-frontend/src/app/common/component/icon/svg-icon.component.html
  discovery-frontend/src/app/common/component/icon/svg-icon.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
  discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
  discovery-frontend/src/app/domain/data-preparation/pr-dataset.ts
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDataset.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Labels: @dataprep, testbed3

#1682 #1049 Add linked source geo type preview message
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-data-preview.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-data-preview.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.html
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/component/storage-filter-select-box.component.html
  discovery-frontend/src/app/data-storage/data-source-list/component/storage-filter-select-box.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/data-source-create.module.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-select-data/staging-db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/data-grid-data-source/data-grid-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/data-grid-data-source/data-grid-data-source.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/detail-data-source.component.ts
  discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.ts
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.02Workbook_Dashboard_dataview.css
  discovery-frontend/src/assets/css/polaris.v2.component.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @datasource, testbed1

#1723 Fix field length in datasource create snapshot preview
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/snapshot-source/snapshot-preview.component.html
Labels: @datasource, bug, testbed3

#1729 fn-add support dimension type : TEXT
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
Labels: @datasource, testbed3

#1725 #1717 Fix ruleIdx when sending rename transform api
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
Labels: @dataprep, testbed4

#1727 Add file name in file datasource detail page
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/LocalFileIngestionInfo.java
Labels: @datasource, bug, testbed1

#1718 #1711 Embedded chart implementation error when parameter is long
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceQueryHistory.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceQueryHistoryRepositoryTest.java
Labels: @datasource, testbed2

#1708 F#540 better hadoop conf errmsg
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepAsyncConfig.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepHdfsService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepPreviewLineService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrTransformRule.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyOrcWriter.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/ColumnType.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyUtil.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Util.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/Histogram.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepHistogramResponse.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepHistogramService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/Revision.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/RevisionSet.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvInputTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/HistogramTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/OrcTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/TeddyAsyncConfigTest.java
Labels: @dataprep, testbed5

#1734 Fix connection error in create datasource step
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
  discovery-frontend/src/app/data-storage/component/connection/connection.component.html
  discovery-frontend/src/app/data-storage/component/connection/connection.component.ts
  discovery-frontend/src/app/data-storage/data-connection/create-connection.component.ts
  discovery-frontend/src/app/data-storage/data-connection/update-connection.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/data-source-create.module.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/data-grid-data-source/data-grid-data-source.component.ts
  discovery-frontend/src/app/data-storage/data-storage-share.module.ts
  discovery-frontend/src/app/data-storage/data-storage.module.ts
  discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
  discovery-frontend/src/app/data-storage/service/storage.service.ts
  discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
  discovery-frontend/src/app/domain/datasource/datasource.ts
  discovery-frontend/src/app/workbench/component/detail-workbench/workbench-login/workbench-login.component.ts
  discovery-frontend/src/app/workbench/workbench.component.ts
Labels: @datasource, bug, testbed2

#1732 Add Filter Criteria for Extended Connections
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java
Labels: @datasource, testbed3

#1737 Fix file validation error in datasource create
  discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
  discovery-frontend/src/assets/css/polaris.v2.page.css
Labels: @datasource, bug, testbed3

#1741 #1735 create new directory without schema problem
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
Labels: @dataprep, testbed5

#1736 Log when granting permission to the datasource and dataconnection
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStream.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/spec/ActivityType.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionEventHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceEventHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceRepository.java
Labels: testbed2

#1726 Fixed an error when adding a map operation with a spatial operation to a dashboard
  discovery-frontend/src/app/common/component/chart/option/define/map/map-common.ts
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
  discovery-frontend/src/app/page/chart-style/map/map-format-option.component.ts
  discovery-frontend/src/app/page/component/analysis/map-spatial/map-spatial.component.html
  discovery-frontend/src/app/page/component/analysis/map-spatial/map-spatial.component.ts
  discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.html
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
Labels: @chart, testbed1

#1749 #1295 none auth connection properties handle
  discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/connector/AbstractJdbcConnector.java
Labels: @datasource, testbed5

#1744 Fix a bug in the dashboard
  discovery-frontend/src/app/common/component/abstract.component.ts
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-relation.component.html
  discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.html
  discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
  discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
  discovery-frontend/src/app/page/page.component.html
  discovery-frontend/src/app/page/page.component.ts
  discovery-frontend/src/app/workbench/component/detail-workbench/workbench-login/workbench-login.component.ts
  discovery-frontend/src/app/workbench/workbench.component.ts
  discovery-frontend/src/app/workspace/component/management/create-workspace.component.ts
  discovery-frontend/src/app/workspace/component/management/workspace-list.component.ts
  discovery-frontend/src/assets/css/polaris.v2.layout.css
  discovery-frontend/src/assets/css/polaris.v2.page.css
  discovery-frontend/src/assets/images/img_db/ic_DB.png
  discovery-frontend/src/assets/images/img_db/ic_db_custom.png
  discovery-frontend/src/assets/images/img_db/ic_db_custom_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_druid.png
  discovery-frontend/src/assets/images/img_db/ic_db_druid_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_hive.png
  discovery-frontend/src/assets/images/img_db/ic_db_hive_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_mysql.png
  discovery-frontend/src/assets/images/img_db/ic_db_mysql_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_oracle.png
  discovery-frontend/src/assets/images/img_db/ic_db_oracle_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_phoenix.png
  discovery-frontend/src/assets/images/img_db/ic_db_phoenix_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_post.png
  discovery-frontend/src/assets/images/img_db/ic_db_post_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_presto.png
  discovery-frontend/src/assets/images/img_db/ic_db_presto_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_rds.png
  discovery-frontend/src/assets/images/img_db/ic_db_rds_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_tibero.png
  discovery-frontend/src/assets/images/img_db/ic_db_tibero_w.png
  discovery-frontend/src/assets/images/img_db/ic_db_w.png
Labels: @dashboard, @workspace, testbed3

#1761 Fix hive desc statement null point exception
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/HiveDataAccessor.java
Labels: @datasource, testbed5

#1751 Fix sorting error in snapshot list
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
Labels: @dataprep

#1753 Fix some translations in dataprep
  discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.html
  discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.ts
  discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
  discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
  discovery-frontend/src/assets/css/polaris.v2.component.css
  discovery-frontend/src/assets/i18n/ko.json
Labels: @dataprep, testbed4

#1755 Fix dataset creation error
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
Labels: @dataprep, testbed2

#1756 Fix radio btn event modified in notebook html
  discovery-frontend/src/app/notebook/component/create-notebook-api/create-notebook-api.component.html
  discovery-frontend/src/app/workspace/component/etc/set-notebook-server.component.html
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @notebook, bug, testbed3

#1767 Selected items must not refresh after sorting or searching
  discovery-frontend/src/app/data-preparation/component/dataset-summary.component.html
  discovery-frontend/src/app/data-preparation/component/dataset-summary.component.ts
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.html
  discovery-frontend/src/app/data-preparation/component/long-update-popup.component.ts
  discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/union-add-datasets/union-add-datasets.component.ts
Labels: @dataprep, testbed2
