Repository metatron-app/metatron-discovery, pull requests merged in 2020-10, with the labels that each got.

#3424 #3423 Remove unnecessary pagewidget configuration changing(Filter's datasource name)
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
Labels: testbed1

#3428 #3427 Hot fix for #3411 Remove variable unUsedVirtualColumnName.
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectMetaQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TimeseriesQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TopNQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
  discovery-server/src/test/java/app/metatron/discovery/query/druid/AbstractQueryBuilderTest.java
  discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java
Labels: bug, testbed2

#3430 #3429 Move spec temporary from parameter to json.
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpec.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpecBuilder.java
Labels: bug, testbed1

#3435 F#3431 Bugfix for prediction of user-defined field
  discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
  discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/CovarianceQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SegmentMetaDataQueryBuilder.java
Labels: bug, testbed1

#3438 #3432 enhance oauth client logout
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
Labels: @common, testbed2

#3439 #3420 Users have workbench permissions if there are connections available
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java
Labels: testbed1

#3442 #3417 remove POST handler overriding on data snapshots
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
Labels: @dataprep, testbed1

#3441 #3436 Fix for invalid initializing measure-filter
  discovery-frontend/src/app/dashboard/filters/bound-filter/bound-filter-panel.component.ts
  discovery-frontend/src/app/dashboard/filters/bound-filter/configure-filters-bound.component.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
Labels: bug, testbed2

#3445 F#3443 improvements of autocompletion in the fomula pane
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
  discovery-frontend/src/lib/at/jquery.atwho.js
Labels: enhancement, testbed1

#3458 #3455 fix alias for values with multi datasources
  discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
  discovery-frontend/src/app/page/page-view.component.ts
  discovery-frontend/src/app/page/page.component.ts
Labels: @chart, testbed1

#3460 #3456 Replace private workspace name with user's fullname
  discovery-frontend/src/app/workspace/workspace.component.ts
Labels: enhancement, testbed1

#3464 #3463 fix existing user defined field when using multi datasource
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
  discovery-frontend/src/app/page/page.component.ts
Labels: @chart, testbed2

#3467 #3466 check datasource status including failed datasource
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/DataSourceCheckJob.java
Labels: @datasource, testbed1

#3475 fix for user field list when changing datasource
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
Labels: @chart, testbed1
