Repository metatron-app/metatron-discovery, pull requests merged in 2020-11, with the labels that each got.

#3477 enable dataset, dataflow in data preparation
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
Labels: @dataprep, testbed1

#3492 #3491 fix embedded view with multi datasources
  discovery-frontend/src/app/embedded/page/embedded-page.component.ts
Labels: @chart, testbed1

#3512 Fixed NPE error when searching using period granularity
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/test/java/app/metatron/discovery/core/oauth/OAuthRequest.java
  discovery-server/src/test/java/app/metatron/discovery/core/oauth/OAuthTestExecutionListener.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
Labels: testbed1

#3516 #3515 change the initial value of time filter on the Engine Monitoring Query tab
  discovery-frontend/src/app/engine-monitoring/query/query.component.ts
Labels: @engine-monitoring, testbed1

#3514 Fixes an issue where members are not deleted in Organization when a user or group is deleted
  discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/org/OrganizationMemberRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/org/OrganizationService.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/KafkaTuningConfig.java
  discovery-server/src/test/java/app/metatron/discovery/core/oauth/OAuthTestExecutionListener.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/user/UserRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/user/group/GroupRestIntegrationTest.java
  discovery-server/src/test/resources/sql/test_group_delete.sql
  discovery-server/src/test/resources/sql/test_group_list.sql
  discovery-server/src/test/resources/sql/test_mail_user.sql
  discovery-server/src/test/resources/sql/test_organization.sql
  discovery-server/src/test/resources/sql/test_user_delete.sql
Labels: testbed2

#3519 fix query_message column's dataType to MEDIUMTEXT
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceQueryHistory.java
  discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
Labels: testbed1
