Repository metatron-app/metatron-discovery, pull requests merged in 2020-04, with the labels that each got.

#3158 F#3157 improve configure schema performance
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
Labels: @datasource, @metadata, testbed2

#3156 The open target of the lnb menu supports "new tab" and "frame" types
  discovery-frontend/src/app/common/domain/extension.ts
  discovery-frontend/src/app/external/external-page.component.ts
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionProperties.java
Labels: testbed1

#3160 change line chart sampling option
  discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
Labels: @chart, testbed2

#3167 change background and logo image in the external login page
  discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
  discovery-server/src/main/resources/templates/api/oauth/login.html
Labels: @common, testbed3

#3186 Fix snapshot list projection
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshotProjections.java
Labels: @dataprep, testbed3

#3173 When moving a workbook, always check the permission of the target workspace
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspacePredicate.java
Labels: testbed1

#3184 fix engine server list initialization
  discovery-frontend/src/app/engine-monitoring/datasource/datasource.component.html
  discovery-frontend/src/app/engine-monitoring/datasource/datasource.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/EngineMonitoringSetter.java
Labels: @engine-monitoring, testbed3

#3182 #3181 fix script error when pie chart and table chart contain alias
  discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
  discovery-frontend/src/app/common/component/chart/type/pie-chart.component.ts
Labels: @chart, testbed2

#3192 #3191 customized external login page
  discovery-server/src/main/asciidoc/application-config-guide.adoc
  discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/OauthClientInformation.java
  discovery-server/src/main/resources/templates/api/oauth/login.html
Labels: @common, testbed3

#3190 #3183 password check at server side
  discovery-frontend/src/app/user/login/component/join/join.component.ts
  discovery-frontend/src/app/user/profile/change-password/change-password.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/user/User.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserErrorCodes.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserPasswordProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserService.java
  discovery-server/src/test/java/app/metatron/discovery/domain/user/UserPasswordRestIntegrationTest.java
Labels: @common, testbed1

#3193 fix initial oauth client details
  discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
  discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
Labels: @common, testbed2

#3200 #3098 New function added for login history management
  discovery-frontend/src/app/admin/user-management/component/access/user-management-access.component.html
  discovery-frontend/src/app/admin/user-management/component/access/user-management-access.component.ts
  discovery-frontend/src/app/admin/user-management/service/members.service.ts
  discovery-frontend/src/app/admin/user-management/user-management.component.html
  discovery-frontend/src/app/admin/user-management/user-management.component.ts
  discovery-frontend/src/app/admin/user-management/user-management.module.ts
  discovery-frontend/src/app/common/component/modal/confirm-small/confirm-small.component.html
  discovery-frontend/src/app/common/component/modal/confirm-small/confirm-small.component.ts
  discovery-frontend/src/app/domain/user/activity.ts
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.html
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
  discovery-frontend/src/app/layout/layout/layout.module.ts
  discovery-frontend/src/app/user/access-history/access-history.component.html
  discovery-frontend/src/app/user/access-history/access-history.component.ts
  discovery-frontend/src/app/user/login/login.component.html
  discovery-frontend/src/app/user/login/login.component.ts
  discovery-frontend/src/app/user/service/activity.service.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/common/saml/SAMLTokenConverter.java
  discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
  discovery-server/src/main/java/app/metatron/discovery/config/OAuthInterceptor.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStream.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamPredicate.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/activities/spec/ActivityType.java
  discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
Labels: @common, testbed1
