Repository metatron-app/metatron-discovery, pull requests merged in 2020-01, with the labels that each got.

#3003 #3002 exclude plupload module
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.html
  discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-upload.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.html
  discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.ts
  discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-confirm-grid.component.ts
  discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-upload-file.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
Labels: testbed3

#2976 #2954 Improvements for real-time dashboard
  discovery-frontend/src/app/common/component/chart/base-chart.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.html
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
  discovery-frontend/src/app/dashboard/update-dashboard.component.ts
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
  discovery-frontend/src/app/domain/dashboard/widget/page-widget.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @dashboard, testbed4

#3011 #2805 Improved overview screen on data exploration
  discovery-frontend/src/app/explore-data/explore-data/component/catalog-folder.component.html
  discovery-frontend/src/app/explore-data/explore-data/explore-data-lnb.component.html
  discovery-frontend/src/app/explore-data/explore-data/explore-data-lnb.component.ts
  discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.html
  discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.ts
  discovery-frontend/src/assets/css/metatron/page.css
  discovery-frontend/src/assets/css/theme_dark/metatron/page.css
  discovery-frontend/src/assets/images/icon_delete.png
Labels: @metadata, testbed3

#3010 #2856 improve mdm screen admin
  discovery-frontend/src/app/common/common.module.ts
  discovery-frontend/src/app/explore-data/explore-data.module.ts
  discovery-frontend/src/app/meta-data-management/code-table/popup/popup-code-table.component.html
  discovery-frontend/src/app/meta-data-management/code-table/popup/popup-code-table.component.ts
  discovery-frontend/src/app/meta-data-management/column-dictionary/popup/popup-column-dictionary.component.html
  discovery-frontend/src/app/meta-data-management/column-dictionary/popup/popup-column-dictionary.component.ts
  discovery-frontend/src/app/meta-data-management/component/choose-code-table/choose-code-table.component.html
  discovery-frontend/src/app/meta-data-management/component/choose-code-table/choose-code-table.component.ts
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
  discovery-frontend/src/app/meta-data-management/detail/detail.module.ts
  discovery-frontend/src/app/meta-data-management/meta-data-management.module.ts
  discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-information.component.html
  discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-information.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/metadata-detail.component.html
  discovery-frontend/src/assets/css/layout.css
  discovery-frontend/src/assets/css/metatron/component/component.button.css
  discovery-frontend/src/assets/css/metatron/component/component.table.css
  discovery-frontend/src/assets/css/metatron/page.css
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
Labels: @metadata, testbed6

#3013 fix column type of metadata to be same as filter type
  discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
Labels: testbed3

#3014 Fix user image display error and icon display error
  discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.ts
  discovery-frontend/src/app/common/component/abstract.component.ts
  discovery-frontend/src/app/explore-data/favorite/data-creator-detail.component.html
  discovery-frontend/src/app/explore-data/favorite/data-creator-detail.component.ts
  discovery-frontend/src/app/explore-data/favorite/data-creator.component.html
  discovery-frontend/src/app/explore-data/favorite/data-creator.component.ts
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/metadata.component.html
  discovery-frontend/src/assets/css/metatron/page.css
  discovery-frontend/src/assets/css/theme_dark/metatron/page.css
Labels: @metadata, testbed3

#3016 Fix user image display error, fix time display error
  discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.html
  discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.ts
  discovery-frontend/src/app/explore-data/favorite/data-creator-detail.component.html
  discovery-frontend/src/assets/css/metatron/page.css
  discovery-frontend/src/assets/css/theme_dark/metatron/page.css
Labels: @metadata, testbed3

#3029 #3022 add cors config for oauth
  discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
Labels: @common, testbed3

#2998 #2997 Workbench schema information Data tab query error
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/HiveDialect.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
Labels: @workbench, testbed2

#3036 #3035 Configurable Consumer
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
  discovery-server/src/main/resources/application.yaml
Labels: testbed3

#3048 #3045 decrypt password in welcome email
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
Labels: @common, need to cherry-pick, testbed3
