Repository metatron-app/metatron-discovery, pull requests merged in 2020-09, with the labels that each got.

#3353 #3346 fix map chart with multi datasources
  discovery-frontend/src/app/datasource/service/datasource.service.ts
Labels: @chart, @dashboard, testbed1

#3360 #3357 support sql query results in Geojson format
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/AbstractEngineRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/DruidEngineRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineProperties.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
  discovery-server/src/main/resources/application.yaml
Labels: testbed1

#3362 F#3361 associated linked datasource
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
  discovery-frontend/src/app/dashboard/util/filter.util.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-frontend/src/app/shared/datasource-metadata/service/constant.service.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/datasource/MultiDataSource.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
  discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/datasource/MultiDataSourceTest.java
Labels: bug, testbed2

#3364 Add projection to workspace and book
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/BookProjections.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/BookTreeService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceProjections.java
Labels: @workspace, testbed2

#3366 #3365 association edit view
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.ts
  discovery-frontend/src/app/domain/dashboard/dashboard.ts
Labels: testbed2

#3363 fix script error in embedded view
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/embedded/page/embedded-page.component.ts
Labels: @chart, testbed1

#3368 #3367 When temporary datasource exists, read from temporary datasource first
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
Labels: testbed2

#3373 #3372 Check the status of the datasource that failed to ingest
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/DataSourceCheckJob.java
Labels: @datasource

#3376 #3370 Bug fix for creator pane in data explorer
  discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.html
  discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.ts
  discovery-frontend/src/app/meta-data-management/metadata/service/metadata.service.ts
Labels: bug, testbed2

#3375 #3374 Prediction of line chart does not work.
  discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java
Labels: bug, testbed1

#3381 #3379 query information in engine monitoring
  discovery-frontend/src/app/engine-monitoring/query/query.component.html
  discovery-frontend/src/app/engine-monitoring/query/query.component.ts
  discovery-frontend/src/app/engine-monitoring/service/engine.service.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringService.java
  discovery-server/src/main/resources/application.yaml
Labels: @engine-monitoring, testbed2

#3383 #3382 bugfix non-existing temporary datasource cleansing and some code cleansing
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceTemporaryRepository.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/TemporaryCleanJob.java
Labels: bug, testbed1

#3384 deprecate dataset, dataflow in data preparation
  discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
  discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
Labels: @dataprep, testbed2

#3390 fix widget_conf column's dataType to MEDIUMTEXT
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/Widget.java
  discovery-server/src/main/resources/db/changelog/db.changelog-master.xml
  discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
Labels: testbed1

#3391 treat measure double NaN
  discovery-frontend/src/app/dashboard/widgets/abstract-widget.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java
Labels: @chart, testbed2

#3396 Addition of processing logic when null is included in Double type result
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java
Labels: testbed1

#3398 #3397 fix user defined field duplicated in multi datasources
  discovery-frontend/src/app/page/page.component.ts
Labels: @chart, testbed2

#3404 exclude from login lock when login fail of whitelist users
  discovery-server/src/main/asciidoc/application-config-guide.adoc
  discovery-server/src/main/java/app/metatron/discovery/common/oauth/CustomDaoAuthenticationProvider.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserPasswordProperties.java
Labels: @common, testbed1

#3406 #3401 Bug fix for wrong generated Druid query for countd expression in user defined field.
  discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/DistinctSketchAggregation.java
  discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
  discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java
Labels: bug, testbed1

#3412 #3411 Making a user-defined column reference another user-defined column
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectMetaQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TimeseriesQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TopNQueryBuilder.java
Labels: testbed1

#3415 #3408 add exception, querytime to query information
  discovery-frontend/src/app/engine-monitoring/query/query.component.html
  discovery-frontend/src/app/engine-monitoring/query/query.component.ts
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringService.java
Labels: testbed2

#3416 reset password failure count when user is activated
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
Labels: @common, testbed1
