Repository metatron-app/metatron-discovery, pull requests merged in 2020-08, with the labels that each got.

#3306 #3305 Apply limit clause for sampling druid table
  discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/query/NativeCriteria.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataService.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionServiceTest.java
Labels: testbed1

#3309 fix external login in ie11
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
  discovery-server/src/main/resources/templates/api/oauth/login.html
Labels: @common, testbed1

#3320 fix mobile external login page
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Bold.eot
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Bold.ttf
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Bold.woff
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Light.eot
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Light.ttf
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Light.woff
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Regular.eot
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Regular.ttf
  discovery-server/src/main/resources/templates/api/static/fonts/SpoqaHanSans-Regular.woff
  discovery-server/src/main/resources/templates/api/static/login.css
Labels: @common, testbed2

#3316 fix creating new custom fields when re-entering the chart editing page
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
Labels: @chart, @dashboard, testbed1

#3331 #3327 fix linked datasource check
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
Labels: @dashboard, testbed1

#3343 F#3342 treat string measure
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java
Labels: testbed1

#3347 #3344 Change timestamp field's name to __time in user defined field with some code cleansing
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/GenericMaxAggregation.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/GenericMinAggregation.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/TimestampEnableAggregator.java
  discovery-server/src/test/java/app/metatron/discovery/query/druid/AbstractQueryBuilderTest.java
  discovery-server/src/test/java/app/metatron/discovery/query/druid/aggregations/GenericMinAggregationTest.java
Labels: testbed2

#3351 F##3344 change timestampfield time
  discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/GenericMaxAggregation.java
  discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/GenericMinAggregation.java
  discovery-server/src/test/java/app/metatron/discovery/query/druid/aggregations/GenericMinAggregationTest.java
Labels: bug, testbed2
