Repository metatron-app/metatron-discovery, pull requests merged in 2021-05, with the labels that each got.

#3656 #3637 add subtotal grid
  discovery-frontend/src/app/common/component/chart/option/ui-option/ui-grid-chart.ts
  discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
  discovery-frontend/src/app/page/chart-style/calc-option.component.html
  discovery-frontend/src/app/page/chart-style/calc-option.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
  discovery-frontend/src/lib/pivot-grid/pivot.view.css
Labels: @chart, testbed1

#3664 fix generating query without sqlName property
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
Labels: testbed1

#3678 F#3639 combine chart sub axis
  discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
  discovery-frontend/src/app/domain/workbook/configurations/field/field.ts
  discovery-frontend/src/app/page/chart-style/format/abstract-format-item.component.ts
  discovery-frontend/src/app/page/chart-style/format/format-item.component.html
  discovery-frontend/src/app/page/page-pivot/page-pivot-format.component.html
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
  discovery-frontend/src/assets/i18n/ko.json
Labels: @chart, testbed2

#3682 fix error embedded dashboard
  discovery-frontend/src/app/embedded/dashboard/embedded-dashboard.component.ts
  discovery-frontend/src/app/embedded/dashboard/presentation-dashboard.component.ts
Labels: @dashboard, testbed1

#3683 Fn fix script error
  discovery-frontend/src/app/common/component/grid/grid.component.ts
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.html
  discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
  discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts
Labels: @dashboard, @workbench, testbed2

#3686 fix to find secondary axis in combine chart
  discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
Labels: @chart, testbed1

#3690 #3668 improve grid chart performance
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
Labels: @chart, testbed1

#3695 F#3691 set countd aggregation in widget
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
  discovery-frontend/src/app/domain/workbook/configurations/field/measure-field.ts
  discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.ts
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
Labels: @chart, testbed1

#3694 Fixed an error with creating value aliases.
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-frontend/src/app/page/page.component.html
  discovery-frontend/src/app/page/page.component.ts
  discovery-frontend/src/app/workbook/workbook.component.ts
Labels: @chart, testbed2

#3696 fix grid sort icon
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
  discovery-frontend/src/assets/css/metatron/component/component.icons.css
  discovery-frontend/src/assets/images/icon_tagview.png
  discovery-frontend/src/assets/images/icon_widget.png
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
Labels: @chart, testbed1

#3698 fix grid sort and header button tooltip
  discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
  discovery-frontend/src/lib/pivot-grid/pivot.view.css
Labels: @chart, testbed1
