Repository metatron-app/metatron-discovery, pull requests merged in 2021-04, with the labels that each got.

#3630 #3613 added saving grid width
  discovery-frontend/src/app/common/component/chart/option/ui-option/ui-grid-chart.ts
  discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
  discovery-frontend/src/app/page/page.component.ts
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
  discovery-frontend/src/lib/pivot-grid/pivot.view.css
Labels: @chart, testbed1

#3645 #3644 Support the aggregation type of thetaSketch in data ingestion
  discovery-frontend/src/app/common/component/abstract.component.ts
  discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
  discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.html
  discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
  discovery-frontend/src/app/data-storage/component/schema-configure/schema-configure-field-detail.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.ts
  discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
  discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
  discovery-frontend/src/app/domain/datasource/datasource.ts
  discovery-frontend/src/app/domain/workbook/configurations/field/measure-field.ts
  discovery-frontend/src/app/page/page.component.html
  discovery-frontend/src/app/shared/datasource-metadata/domain/type.ts
  discovery-frontend/src/app/shared/datasource-metadata/service/constant.service.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/common/datasource/DataType.java
  discovery-server/src/main/java/app/metatron/discovery/common/datasource/LogicalType.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/MeasureField.java
Labels: testbed2

#3647 Dashboard router fragment function was added.
  discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-complete.component.ts
  discovery-frontend/src/app/workbook/workbook.component.html
  discovery-frontend/src/app/workbook/workbook.component.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-frontend/src/lib/nicEdit/nicEdit.js
Labels: @dashboard, testbed1

#3648 [Hotfix] Remove codes to check whether mobile resources exist
  discovery-server/src/main/java/app/metatron/discovery/domain/mobile/MobileController.java
  discovery-server/src/test/java/app/metatron/discovery/domain/mobile/MobileRestIntegrationTest.java
  discovery-server/src/test/resources/config/mobile-config.properties
  discovery-server/src/test/resources/html/index.html
Labels: testbed2

#3649 fix compile error after poi bump
  discovery-server/src/main/java/app/metatron/discovery/util/ExcelUtils.java
Labels: testbed2

#3652 #3651 Fixed that the widget filter is changed to a global filter after copying the widget
  discovery-frontend/src/app/dashboard/update-dashboard.component.ts
Labels: @dashboard, testbed2

#3654 Add API to change stream datasource information(ingestion spec.and field)
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSource.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceEventHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/IngestionUpdateRequest.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/HdfsIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/HiveIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/IngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/LocalFileIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/RealtimeIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/BatchIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/LinkIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SingleIngestionInfo.java
  discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineIngestionService.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/KafkaRealTimeIndex.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/KafkaRealTimeIndexBuilder.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java
Labels: testbed2
