Repository metatron-app/metatron-discovery, pull requests merged in 2021-08, with the labels that each got.

#3824 Fixed a script error that occurred when modifying the color of a measure value in a grid chart
  discovery-frontend/src/app/page/chart-style/color-option.component.ts
Labels: @chart, testbed2

#3826 #3822 Russian language pack
  discovery-frontend/src/app/admin/user-management/component/members/change-workspace-owner-modal/change-workspace-owner-modal.component.html
  discovery-frontend/src/app/app.component.ts
  discovery-frontend/src/app/common/value/user.setting.value.ts
  discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.html
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/ru.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
Labels: testbed2

#3829 #3828 Nested object in tuningConfig should be overrided
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/IngestionSpecBuilder.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/index/IndexSpec.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/AbstractTuningConfig.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/BatchTuningConfig.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/HadoopTuningConfig.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/KafkaTuningConfig.java
  discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
Labels: testbed3

#3831 Fix filtering in presentation view
  discovery-frontend/src/app/embedded/dashboard/presentation-dashboard.component.html
Labels: testbed2

#3834 #3833 Fix secondary axis setting error
  discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
  discovery-frontend/src/app/page/chart-style/yaxis-option.component.ts
  discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
  discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
Labels: testbed2, @chart

#3842 fix UPE in tuningConfig
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/AbstractTuningConfig.java
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/BatchTuningConfig.java
  discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
Labels: testbed2

#3847 #3837 Added password change function in user management page
  discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.html
  discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.ts
  discovery-frontend/src/app/admin/user-management/service/members.service.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/ru.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
Labels: testbed1

#3848 #3544 Added member sign-up to external login page and added organization input function when registering as a member
  discovery-frontend/src/app/domain/user/user.ts
  discovery-frontend/src/app/user/login/component/join/join.component.html
  discovery-frontend/src/app/user/login/component/join/join.component.ts
  discovery-frontend/src/app/user/service/user.service.ts
  discovery-frontend/src/assets/i18n/en.json
  discovery-frontend/src/assets/i18n/ko.json
  discovery-frontend/src/assets/i18n/ru.json
  discovery-frontend/src/assets/i18n/zh.json
  discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/User.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserErrorCodes.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/org/Organization.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/org/OrganizationController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/role/Role.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/role/RoleService.java
  discovery-server/src/main/resources/db/changelog/discovery.changelog-2021.3.xml
  discovery-server/src/main/resources/logback-console.xml
  discovery-server/src/main/resources/messages/messages.properties
  discovery-server/src/main/resources/messages/messages_en.properties
  discovery-server/src/main/resources/messages/messages_ko.properties
  discovery-server/src/main/resources/templates/api/oauth/join.html
  discovery-server/src/main/resources/templates/api/oauth/login.html
  discovery-server/src/main/resources/templates/api/oauth/reset-password.html
  discovery-server/src/main/resources/templates/api/static/images/btn_popclose.png
  discovery-server/src/main/resources/templates/api/static/images/icon_info.png
  discovery-server/src/main/resources/templates/api/static/images/icon_message.png
  discovery-server/src/main/resources/templates/api/static/login.css
  discovery-server/src/main/resources/templates/api/static/mobile.css
Labels: testbed2

#3860 #3859 Added Russian rouble
  discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
  discovery-frontend/src/app/common/component/chart/option/define/common.ts
  discovery-frontend/src/app/page/chart-style/format/abstract-format-item.component.ts
Labels: testbed2

#3832 Add validation for checking duplicated field
  discovery-common/src/main/java/app/metatron/discovery/common/exception/GlobalErrorCodes.java
  discovery-server/src/main/java/app/metatron/discovery/common/exception/GlobalExceptionHandler.java
  discovery-server/src/main/java/app/metatron/discovery/common/exception/ValidationException.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSource.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/validation/DuplicatedFieldValidation.java
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/validation/DuplicatedFieldValidator.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceTest.java
Labels: testbed3

#3858 #3857 Removed the API for querying filter candidate values from the dashboard query screen.
  discovery-frontend/src/app/app.component.ts
  discovery-frontend/src/app/dashboard/component/selection-filter/selection-filter.component.ts
  discovery-frontend/src/app/workbook/workbook.component.ts
  discovery-frontend/src/assets/css/lib/dnd/style.css
Labels: @dashboard, testbed1

#3863 fix bug with file input stream
  discovery-server/src/main/java/app/metatron/discovery/util/PolarisUtils.java
Labels: testbed2

#3870 #3859 Added Russian rouble in grid chart
  discovery-frontend/src/lib/pivot-grid/pivot.grid.min.js
Labels: testbed1, @chart
