Repository metatron-app/metatron-discovery, pull requests merged in 2022-02, with the labels that each got.

#3999 #3977 remove athena jdbc dependency
  discovery-extensions/athena-connection/README.md
  discovery-extensions/athena-connection/pom.xml
  discovery-extensions/athena-connection/src/main/assembly/assembly.xml
  discovery-extensions/pom.xml
Labels: testbed1

#3989 #3907 datasource mapbox preview
  discovery-frontend/angular.json
  discovery-frontend/package.json
  discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
  discovery-frontend/src/app/common/interceptor/loader-interceptor.ts
  discovery-frontend/src/app/common/service/common.service.ts
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
  discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
  discovery-frontend/src/app/datasource/service/datasource.service.ts
  discovery-frontend/src/app/domain/dashboard/dashboard.ts
  discovery-frontend/src/styles.css
  discovery-server/src/main/asciidoc/application-config-guide.adoc
  discovery-server/src/main/java/app/metatron/discovery/domain/properties/PropertyController.java
Labels: @datasource, testbed2

#4000 fix download chart data with timestamp field that is a dimension role
  discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/SearchQueryRequest.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/TimestampField.java
Labels: testbed1, @chart

#4001 add websocket disconnection when is onbeforeunload called
  discovery-frontend/proxy.conf.js
  discovery-frontend/src/app/common/component/abstract.component.ts
Labels: @common, testbed2

#4005 Fix global filter in dashboard of multi datasources with association
  discovery-frontend/src/app/dashboard/util/dashboard.util.ts
Labels: testbed1, @chart

#4012 Remove 'X' button when showing access log dialog on log-in page
  discovery-server/src/main/resources/templates/api/oauth/login.html
Labels: testbed2
