Repository metatron-app/metatron-discovery, pull requests merged in 2022-04, with the labels that each got.

#4020 Add a set for the dockerizing
  README.md
  discovery-distribution/bin/common.sh
  discovery-distribution/bin/metatron.sh
  discovery-distribution/docker/.dockerignore
  discovery-distribution/docker/Dockerfile
  discovery-distribution/docker/entrypoint.sh
  discovery-server/pom.xml
Labels: @common

#4026 Improve email template for password reset
  discovery-server/src/main/java/app/metatron/discovery/common/Mailer.java
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/auth/OauthClientInformation.java
  discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
  discovery-server/src/main/resources/messages/messages.properties
  discovery-server/src/main/resources/messages/messages_en.properties
  discovery-server/src/main/resources/messages/messages_ko.properties
  discovery-server/src/main/resources/templates/api/email/user_reset_password.html
  discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
  discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
  discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
  discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
  discovery-server/src/main/resources/templates/api/email/user_signup_request.html
  discovery-server/src/main/resources/templates/api/oauth/reset-password.html
  discovery-server/src/test/java/app/metatron/discovery/common/MailerTest.java
  discovery-server/src/test/java/app/metatron/discovery/domain/user/UserRestIntegrationTest.java
Labels: testbed1

#4030 fix discarding null values ​​in timestamp field
  discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
Labels: testbed1

#4032 fix grid chart data csv download with double quotes
  discovery-frontend/src/app/common/component/grid/grid.component.ts
Labels: testbed1

#4033 Add some more logs for changing datasources
  discovery-server/src/main/java/app/metatron/discovery/common/exception/GlobalExceptionHandler.java
  discovery-server/src/main/java/app/metatron/discovery/common/exception/RestExceptionHandler.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/DashBoardController.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/DashBoardService.java
  discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetService.java
Labels: testbed2

#4036 #4035 undefined check for customFields
  discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
Labels: testbed1
